### ISSUE TITLE
Installation Docker Compose

### ISSUE THREAD

**Issue by DavidOliMar** [simonl169/dns-owl#2]
Good evening, first of all thank you for creating this docker. I was looking for how to manage the DynDns of my Strato domain and I have arrived at your GitHub.
It’s the first time I’ve written to someone, so I apologize in advance if I do it wrong or in the wrong place.
I have tried to install the Docker on my Ubuntu server on which I have many others but it gives me the following error when installing it.

Demon error response: extraction access denied for dns-owl, the repository does not exist or may require "docker login": denied: requested access to the resource is denied

In the installation I have only created the config.json file in the root of the docker next to the docker-compose.yml and in it I have put as indicated the following

```
{
  "domains": [
    "midominio.com"
  ]
}
```

I don't know what I'm doing wrong or what else I have to add to make it work.

Thank you very much in advance

**Comment by simonl169** [comment]
Hey!

Seems like Docker cannot find my image.
Since I am using Github instead of Docker Hub, you may need to modify your image name.
Try:
`docker pull ghcr.io/simonl169/dns-owl:v0.1.8`
in your command line or try using 
`ghcr.io/simonl169/dns-owl:v0.1.8`
in the compose file.

**Comment by simonl169** [comment]
You can visit the container page here:
[https://github.com/simonl169/dns-owl/pkgs/container/dns-owl](url)

**Comment by DavidOliMar** [comment]
Perfect, Simon ; ) Thank you very much for your prompt response

I have changed my Compose File for
```
ghcr.io/simonl169/dns-owl:v0.1.8
```
And it worked for me. I'm attaching you as I put it.

```
version: '3.8'
services:
    dns-owl:
        image: ghcr.io/simonl169/dns-owl:v0.1.8
        container_name: DynStrato
        environment:
            - STRATO_DYNDNS_PASSWORD=XXXXXXXXXXXXXXXX
            - TZ=Europe/Madrid
            - CRONVARS2=*/1 * * * *
        volumes:
            - /config.json:/app/config.json
```

It solves the IP correctly but in the Logs it returns the following error

```
by Simon169
###############-------------------------------------
Current Time: 17/07/2023 10:30:00
Getting current public IP address...
My public IP address is: 81.40.XX.XX
###############-------------------------------------
Reading config.json...
    with open('config.json', 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: 'config.json'
```
